---
version: "3"
services:
  eap:
    image: stroopwafel/eap-controller:latest
    container_name: eapcontroller
    volumes:
      - /path/to/your/folder:/current_config
    ports:
      - 8088:8088
      - 8043:8043
      - 27001:27001/udp
      - 27002:27002
      - 29810:29810/udp
      - 29811:29811
      - 29812:29812
      - 29813:29813
    restart: unless-stopped
